### ISSUE TITLE
Use Haskell tar library again

### ISSUE THREAD

**Issue by brandon-leapyear** [brandonchinn178/ztar#21]
We currently hack `Codec.Archive.Tar` because the Haskell library has major bugs. At least the following bugs need to be fixed in order to do this work:

- Preserve executability: haskell/tar#25
- Error if symlink points to directory: haskell/tar#34

Would be nice:

- Unlimited filename length: haskell/tar#1
- Symbolic link to `..` in nested directory: haskell/tar#32
- File path parse error: haskell/tar#35

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

See the `haskell-tar` branch

**Comment by Bodigrim** [comment]
All `tar` tickets have been closed. @brandon-leapyear could you possibly give a try to a release candidate? https://hackage.haskell.org/package/tar-0.6.0.0/candidate

**Comment by brandonchinn178** [comment]
@Bodigrim Thanks! The current test suite actually already works with tar-0.5, so I've gone ahead and switched `master` to use `tar` again anyway.

We've stopped needing ztar for a while, so I don't have anything to test your release candidate against. But now, anyone using ztar will just inherit behavior from upstream tar, so they can test against 0.6
