### ISSUE TITLE
Update to zip-1.0.0

### ISSUE THREAD

**Issue by brandonchinn178** [brandonchinn178/ztar#9]
See the zip-1.0.0 branch. Do not merge until `master` is sufficiently tested and the API is solid.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

Blocked by #18

**Comment by brandonchinn178** [comment]
Fixed by #29?
